name: myapp

spider:
  image: spider:latest
    # 或者使用构建指令来从 Dockerfile 构建镜像
  build:
    context: .
    command: 
      - "python"
      - "main.py"
  environment:  # 设置环境变量
    - POST_HOST=100.95.218.64
    - POST_USER=root
    - POST_PASS=E,*f*YdGgYSgqfze1tLqc0Pm8CK2
    - POST_PORT=44455